/*
*	New C++ Header  File starts here.
*	This file should be named message_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=message.hpp
*
*	.gen script :
*		0:load message.hpp
*		1:clear
*		2:select_from_file message.hpp
*		3:generate C++ protos>message_n_codegen_protos.hh
*		4:generate C++ format>message_n.cc
*		5:generate C++ update>message_n.cc
*		6:generate C++ constructor>message_n.cc
*		7:exit
*
*/

#ifndef message_n_codegen_protos_hh_included
#define message_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "message.hpp"

// Forward Function Prototypes


#ifndef MAX_MESSAGE_NAME_LENGTH
#define MAX_MESSAGE_NAME_LENGTH 8
#endif
#ifndef MESSAGE_NAME_LIST_LENGTH
#define MESSAGE_NAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE message_id_list[MESSAGE_NAME_LIST_LENGTH];
extern const size_t message_size_list[MESSAGE_NAME_LIST_LENGTH];

// Enumerated Type Constants

extern int message_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif message_n_codegen_protos_hh_included */ 

